title: jaYzee 
description: "A page Penetartion testers"
author:
  name: "Jayyvee"
  email: "jayavarshinith@gmail.com"
  url: "https://Jayyveee.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Jayavarshini"
year : "2019"
