title: jaYzeee
description: "A Static site for Introduction and self-works"
author:
  name: "Jayavarshini"
  email: "januthiru26@gmail.com"
  url: "https://jayyveee.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "jaYzeee"
year : "2019"
